[metadata]
name = delta_c
version = 0.1.0
description = Generate a diff between two coverage reports in `llvm-cov`’s text format.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/narpfel/delta-c
license = GPL-3.0
license_files = LICENSE
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: Implementation :: CPython
    Programming Language :: Python :: Implementation :: PyPy

[options]
py_modules = Δc
install_requires =
    Pygments>=2.20.0
python_requires = >=3.14

[options.entry_points]
console_scripts =
    Δc = Δc:main

[bdist_wheel]
universal = true

[flake8]
max-line-length = 99

[tool:isort]
force_single_line = True
