name: pre-commit

on:
  - push
  - pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: pre-commit
        uses: pre-commit/action@v3.0.1
